### ISSUE TITLE
Uable to locate the pdf containing all the chapters of the book

### ISSUE THREAD

**Issue by v6msee** [liyin2015/python-coding-interview#9]
Hey Li yin,
Unable to find the complete book in the repository, previously I have seen the full book. Is it removed intentionally or by chance ?

**Comment by liyin2015** [comment]
Hi, there. Currently we are working on the book and the full book contains too many wip chapters and can be misleading. Will add more chapters when they are ready

**Comment by liyin2015** [comment]
The whole book is provided here: https://github.com/liyin2015/python-coding-interview/blob/master/Easy-Book/main.pdf

**Comment by v6msee** [comment]
@liyin2015 Thank you very much, wait is over :)
